name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your default branch if different

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend  # Set the working directory to 'frontend'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Debug environment variables
        # Debug step to print environment variables (ensure they are sanitized and do not reveal secrets in public repos)
        run: |
          echo "Supabase URL: $NEXT_PUBLIC_SUPABASE_URL"
          echo "Supabase Key: $NEXT_PUBLIC_SUPABASE_ANON_KEY"

      - name: Build frontend project
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        run: npm run build && npm run export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/out  # Path to the exported static files
